name: "EMS Package"
description: "generate production data package for EMS"
inputs:
  exclude-patterns:
    description: "File patterns to exclude from package. Patterns must be white space separated"
    required: false
    default: ""
  access-token:
    description: "Personal access token for private repos"
    required: true
  rclone-params:
    description: "rclone configuration parameters for sharepoint upload"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
        token: ${{ inputs.access-token }}
    - name: Generate filename
      id: ident
      run: |
        mkdir -p ZIP
        repo=$(echo ${{ github.repository }} | cut -d / -f 2)
        zipname=${repo}-${{ github.ref_name }}-$(date +%Y%m%#d%H%M)-ems.zip
        echo "::set-output name=zipname::${zipname}"
        echo "::set-output name=zippath::ZIP/${zipname}"
        echo "::set-output name=reponame::${repo}"
      shell: bash
    - name: ZIP Repo
      uses: ci4rail/zip-action@v1
      with:
        output-path: "${{ steps.ident.outputs.zippath }}"
        exclude-patterns: "${{ inputs.exclude-patterns }}"
    - name: Upload ZIP to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.access-token }}
        file: "${{ steps.ident.outputs.zippath }}"
        asset_name: ${{ steps.ident.outputs.zipname }}"
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload to Sharepoint
      uses: wei/rclone@v1
      env:
        RCLONE_CONF: ${{ inputs.rclone-params }}
      with:
        args: copy ${{ steps.ident.outputs.zippath }} ci4railengineeringdocuments:EMS-ProdData/${{ steps.ident.outputs.reponame }}
